import { redirect } from 'next/navigation'
import React from 'react'

export const metadata = {
  title: "User",
  description: "Generated by create next app",
};

const UserDetails = ({ params }) => {
  console.log(params)
  return (
    <div>
      its me {params.id}
      <p>if my id is 5 then i will redirected to login page</p>

      {params.id === '5' ? redirect('/login') : ''}
    </div>
  )
}

export default UserDetails
